# Generated by Django 5.0 on 2023-12-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cusratingfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusorders',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default="('M', 'Medium')", max_length=2),
        ),
    ]
