# Generated by Django 5.0 on 2023-12-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_cusorders_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CusOrders',
        ),
        migrations.DeleteModel(
            name='CusRatingFeedback',
        ),
    ]
