# Generated by Django 4.2.5 on 2023-12-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0004_item_prod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('m', 'Men'), ('f', 'Women'), ('k', 'Kids')], default="('m', 'Men')", max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media.istockphoto.com/id/1273109788/vector/coming-soon-isolated-vector-icon-paper-style-promotion-sign-start-a-new-business-design.jpg?s=612x612&w=0&k=20&c=0APH6QCc371SuCEYLspgp6oh-tE5-rvbK0dzLMRmJGA=', max_length=500),
        ),
    ]
