# Generated by Django 4.2.5 on 2023-12-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_item_category_alter_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('m', 'Mens'), ('f', 'Womens'), ('k', 'Kids')], default="('m', 'Mens')", max_length=1),
        ),
    ]
