# Generated by Django 5.0 on 2023-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
