# Generated by Django 5.0.1 on 2024-01-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0010_alter_cusorders_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='prod_code',
        ),
        migrations.AlterField(
            model_name='cusorders',
            name='user',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('m', 'Mens'), ('f', 'Womens'), ('k', 'Kids')], default='m', max_length=1),
        ),
    ]
