# Generated by Django 5.0.1 on 2024-01-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0012_remove_cusorders_prod_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusorders',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clothing.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='M', max_length=2),
        ),
    ]
