# Generated by Django 5.0.1 on 2024-01-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_alter_cusorders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cusorders',
            name='order_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Order Confirmed', max_length=20),
        ),
    ]
