# Generated by Django 5.0.1 on 2024-01-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0015_cusorders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusorders',
            name='order_status',
            field=models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Confirmed', max_length=20),
        ),
    ]
